### ISSUE TITLE
[Bug] Badge style broken in notification center

### ISSUE THREAD

**Issue by samedgagger** [CreatureSurvive/consolidation#7] opened 2017-11-20 07:55 UTC
I chose normal badge style but it appears under the icon.

**Comment by CreatureSurvive** [comment] 2017-11-21 21:32
@samedgagger I am aware of this issue, its caused by a bug in the preferences. I will be fixing this in alpha 6.

**Comment by CreatureSurvive** [comment] 2017-12-08 22:20
@samedgagger I just fixed this issue, it will be included in the next release.

**Closed by CreatureSurvive** 2017-12-08 22:20 UTC
